name: Version Bump

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  version-bump:
    name: Bump Version after Merge
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PAT || secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install

      - name: Setup Git User
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: Apply Changesets
        id: changesets
        run: |
          # Apply all pending changesets
          pnpm changeset version
          
          # Check if there are changes after running changeset version
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi
        
      - name: Clean up Changeset Files
        if: steps.changesets.outputs.changes_made == 'true'
        run: |
          # Remove all changeset files except README.md and config.json
          find .changeset -type f -not -name "README.md" -not -name "config.json" -delete
        
      - name: Commit and Push Changes
        if: steps.changesets.outputs.changes_made == 'true'
        run: |
          git add .
          git commit -m "chore: version bump after merge [skip ci]"
          git push 